services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    container_name: wordpress
    restart: always
    environment:
      - WORDPRESS_DB_HOST=${DB_HOST}
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - GIT_EMAIL=${GIT_EMAIL}
      - GIT_NAME=${GIT_NAME}
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_REPO=${GIT_REPO}
      - GIT_PERSONAL_TOKEN=${GIT_PERSONAL_TOKEN}
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mariadb

volumes:
  db_data:
